name: Build FoundryVTT Module

on:
  push:
    tags:
      - 'foundry-mcp-server-v*.*.*'

permissions:
  contents: write

jobs:
  build-foundry-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate module.json
        run: npm run process-template

      - name: Create FoundryVTT module zip
        run: |
          cd foundry-local-rest-api
          zip -r ../foundry-local-rest-api.zip . -x "*.git*" "node_modules/*" "*.DS_Store*" "module.json.template"
          cd ..

      - name: Upload FoundryVTT module artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" foundry-local-rest-api.zip foundry-local-rest-api/module.json
